### ISSUE TITLE
Docs do not match usage

### ISSUE THREAD

**Issue by 5t33** [CrunchyData/terraform-provider-crunchybridge#5]
As you can see the Terraform provider described here:
https://docs.crunchybridge.com/concepts/terraform/

Is used like so:
```
terraform {
  required_providers {
    crunchybridge = {
      source  = "CrunchyData/crunchybridge"
      version = "0.1.0"
    }
  }
}

provider "crunchybridge" {
  // Set these to your API key
  application_secret = "cbkey_abCDefG123450jklMNO987654abcdefGHIJKL123543"
}

```

The docs make no mention of an "application id". However when I run the provider, I get the following:
```
provider.crunchybridge.application_id
  The application id component of the Crunchy Bridge API key.

  Enter a value: 
```

It's expecting an application ID. I'm not sure where to find this.

**Comment by wilybrace** [comment]
@5t33 Steven, the initial version of the Terraform provider was written against an authentication scheme that required the `application_id` which has since been deprecated / retired.

We have an upcoming release that will address this present-day mismatch, but in the meantime you can set the application_id value to any string value (e.g. "`none`") and it should work correctly.

**Comment by wilybrace** [comment]
Release v0.2.0, available via Terraform registry, no longer requires application_id.
